[advisories]
ignore = [
    "RUSTSEC-2020-0071", # Remove once upstream dependencies are updated.
    "RUSTSEC-2021-0124", # Remove once upstream dependencies are updated.
    "RUSTSEC-2022-0093", # Remove once we can update to ed25519-dalek to v2.
]
